server:
  port: 8080
  servlet:
    context-path: /om
spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.255.1:3306/company?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver