server:
  port: 80
  servlet:
    context-path: /om
spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/company?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
