server:
  port: 8080
  servlet:
    context-path: /om
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/company?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: mysqlpwd
    driver-class-name: com.mysql.cj.jdbc.Driver