server:
  port: 80
  servlet:
    context-path: /om
spring:
  # rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri:  mongodb://121.199.72.15:27017/admin
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/**/**
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/company?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 5000
    #数据库
    database: 0
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  mybatis 驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true